### ISSUE TITLE
Pass parameters from rapp to android app

### ISSUE THREAD

**Issue by stonier** [rosjava/android_remocons#18]
This was leftover from a bygone age, not sure it's being used anymore. Example:

```
display: Talker
description: Default ros style talker tutorial
platform: linux.ros.*
launch: rocon_apps/talker.launch
interface: rocon_apps/talker.interface
icon: rocon_apps/rocon_bubble.png
pairing_clients:
 - type: android
   manager:
     api-level: 9
     intent-action: com.github.ros_java.android_apps.listener.Listener
   app:
     gravityMode: 0
     base_control_topic: /cmd_vel
```

Dont know if even the api-level is getting checked. I suspect the app variables are parameters to pass to the app, which would be quite useful.
